### PR TITLE
Shared state

### PR DESCRIPTION
**Pull request by vaprdev**
loads in links from the past 24 hours, across 10 paginated pages. 

todo: search for actual end of pagination, to make sure 10 pages exist. 

example result from `hit_all_pages` would return a vector w/ the following urls: 

```
/building/66-rockwell-place-brooklyn/11g
/building/40-harrison-street-new_york/15k
/building/458-6-avenue-manhattan/4
/building/120-sullivan-street-new_york/b
/building/416-west-23-street-new_york/5c
/building/90-thompson-street-new_york/f5
/building/364-west-30-street-manhattan/5
/building/147-bleecker-street-manhattan/3f
/building/454-west-22-street-new_york/3ccc
/building/300-ashland-place-brooklyn/27n
/building/416-lafayette-street-new_york/3l
/building/101-west-27-street-manhattan/3f
/building/107-waverly-avenue-brooklyn/3r
/building/55-west-8-street-manhattan/6
/building/80-north-moore-street-new_york/4m
/building/156-west-20-street-manhattan/2b
/building/285-court-street-brooklyn/3f
/building/119-7-avenue-new_york/3f
/building/112-8-avenue-new_york/4fn
/building/11-waverly-place-new_york/8k
/building/43-carmine-street-new_york/14
/building/65-morton-street-new_york/5n
/building/165-congress-street-brooklyn/5
/building/89-christopher-street-new_york/17
/building/187-st-james-place-brooklyn/rental/1988315
/building/793-6-avenue-manhattan/2s
/building/48-9-avenue-new_york/27a
/building/203-washington-park-brooklyn/2
/building/356-carlton-avenue-brooklyn/garden
/building/457-west-17-street-manhattan/9a
/building/187-st-james-place-brooklyn/rental/1986177
/building/222-west-10-street-new_york/1b
/building/791-broadway-new_york/3a
/building/107-morton-street-new_york/ga
/building/142-west-17-street-manhattan/2m
/building/209-washington-park-brooklyn/3a
/building/127-st-felix-street-brooklyn/3
/building/315-west-19-street-new_york/51
/building/160-waverly-place-manhattan/5
/building/318-warren-street-brooklyn/rental/1977047
/building/173-court-street-brooklyn/3b
/building/310-greenwich-street-new_york/6m
/building/170-thompson-street-new_york/11
/building/331-west-16-street-manhattan/grdn
/building/156-west-20-street-manhattan/2b
/building/210-west-10-street-new_york/2a1
/building/95-cambridge-place-brooklyn/garden
/building/145-waverly-place-new_york/5a
/building/416-west-23-street-new_york/3a
/building/14-bedford-street-manhattan/2
/building/270-west-12-street-new_york/4c
/building/40-harrison-street-new_york/15k
/building/111-mac-dougal-street-manhattan/16
/building/246-west-20-street-manhattan/1c
/building/146-amity-street-brooklyn/4a
/building/194-spring-street-manhattan/21
/building/203-spring-street-new_york/20
/building/74-grand-avenue-brooklyn/4k
/building/208-west-16-street-new_york/rental/1957187
/building/255-west-19-street-new_york/2
/building/the-refinery/7k
/building/101-7-avenue-south-manhattan/3f
/building/43-jane-street-new_york/3fw
/building/25-cornelia-street-manhattan/10
/building/176-thompson-street-new_york/3a
/building/atrium-coop/9hw
/building/atrium-coop/5bw
/building/310-carlton-avenue-brooklyn/2
/building/237-8-avenue-manhattan/36
/building/78-grand-avenue-brooklyn/5b
/building/108-west-17-street-manhattan/6
/building/51-bank-street-new_york/5
/building/30-horatio-street-new_york/1a
/building/forte-condominium/22d
/building/121-bank-street-new_york/1j
/building/628-hudson-street-manhattan/a
/building/66-rockwell-place-brooklyn/11g
/building/120-st-james-place-brooklyn/rental/1940712
/building/the-clermont-375-myrtle-avenue-brooklyn/4c
/building/the-clermont-375-myrtle-avenue-brooklyn/3e
/building/462-6-avenue-manhattan/22
/building/209-washington-park-brooklyn/3b
/building/the-refinery/2q
/building/322-west-11-street-manhattan/1a
/building/237-west-13-street-new_york/14
/building/18-king-street-manhattan/15b
/building/clermont-greene/414
/building/75-grand-avenue-brooklyn/1b
/building/the-irvin-house/6e
/building/339-west-19-street-new_york/f
/building/412-west-25-street-manhattan/4g
/building/165-christopher-street-new_york/rental/1908830
/building/207-west-11-street-new_york/2d
/building/the-refinery/2c
/building/78-grand-avenue-brooklyn/5a
/building/78-grand-avenue-brooklyn/5d
/building/165-christopher-street-new_york/rental/1888629
/building/246-west-18-street-new_york/12
/building/138-sullivan-street-new_york/1
/building/176-thompson-street-new_york/2d
/building/39-christopher-street-new_york/4d
/building/atrium-coop/1ew
/building/491-hudson-street-manhattan/1
/building/328-west-17-street-new_york/grf
/building/atrium-coop/5gw
/building/atrium-coop/8he
/building/39-christopher-street-new_york/2d
/building/149-sullivan-street-new_york/rental/1836833
/building/234-8-avenue-new_york/8
/building/39-christopher-street-new_york/g2
/building/ohm-312-11-avenue-new_york/19k
```

### CODE REVIEW

**Comment by vaprdev** [comment]
@dax0 good point, i need to add that in

**Comment by thdxr** [comment]
I've written so many reddit crawlers I instantly recognized what you were doing haha

**Comment by vaprdev** [comment]
haha that's funny i was going to write a reddit crawler next to send me like top posts from a couple subs every morning

**Comment by vaprdev** [comment]
wanted to use /r/getmotivated but they're all pictures so i can't parse text

**Pull request merged**
